"""Public template for config.py."""

from __future__ import annotations

import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent


def _load_env_file() -> None:
    env_path = PROJECT_ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


_load_env_file()


DEFAULT_INPUT_PATH = str(PROJECT_ROOT / "dataset" / "final.jsonl")
TIMESTAMP_MILLISECONDS_THRESHOLD = 10_000_000_000
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15
SPLIT_RATIO_EPSILON = 1e-6

COLD_START_STANCE_BIAS = 0.0
COLD_START_CONSISTENCY = 0.5
COLD_START_ACTIVITY = 0.0
COLD_START_INFLUENCE = 0.0
COLD_START_REACTION_CONSISTENCY = 0.0
COLD_START_EMOTION_STABILITY = 0.0
SINGLE_HISTORY_EMOTION_STABILITY = 1.0
PRICE_TIE_COUNTS_AS_BULLISH = True

DEFAULT_DEBATE_ROUNDS = 4

SILICONFLOW_OPENAI_BASE_URL = "https://api.siliconflow.cn/v1"
SILICONFLOW_MODEL = os.getenv("SILICONFLOW_MODEL", "Pro/zai-org/GLM-4.7")
SILICONFLOW_API_KEY = os.getenv("SILICONFLOW_API_KEY", "")
SILICONFLOW_MAX_TOKENS = 1200
SILICONFLOW_TEMPERATURE = 0.2
SILICONFLOW_ENABLE_THINKING = False
SILICONFLOW_TIMEOUT_SECONDS = float(os.getenv("SILICONFLOW_TIMEOUT_SECONDS", "300"))
SILICONFLOW_HTTP_RETRIES = int(os.getenv("SILICONFLOW_HTTP_RETRIES", "5"))
SILICONFLOW_CACHE_ENABLED = True
SILICONFLOW_CACHE_DIR = PROJECT_ROOT / "outputs" / "llm_cache" / "siliconflow"

# Default to the faster text embedding backend. Use finbert only when explicitly requested.
TEXT_EMBEDDING_BACKEND = os.getenv("TEXT_EMBEDDING_BACKEND", "sentencebert")
SENTENCEBERT_MODEL_NAME = os.getenv("SENTENCEBERT_MODEL_NAME", "sentence-transformers/all-MiniLM-L6-v2")
SENTENCEBERT_EMBEDDING_DIM = int(os.getenv("SENTENCEBERT_EMBEDDING_DIM", "384"))
FINBERT_MODEL_NAME = os.getenv("FINBERT_MODEL_NAME", "ProsusAI/finbert")
FINBERT_EMBEDDING_DIM = int(os.getenv("FINBERT_EMBEDDING_DIM", "768"))
TEXT_EMBEDDING_CACHE_DIR = PROJECT_ROOT / "outputs" / "embedding_cache"
HF_MODEL_CACHE_DIR = PROJECT_ROOT / "outputs" / "hf_cache"

DEFAULT_RELATIONS = ["interact"]
MODEL_HIDDEN_DIM = 16
CALIBRATOR_HIDDEN_DIM = 32
ODE_STEPS = 4
EULER_STEP_SIZE = 0.25
ODE_TERMINAL_TIME = 5.0
ODE_METHOD = "dopri5"
ODE_RTOL = 0.01
ODE_ATOL = 0.001
ODE_USE_ADJOINT = False
ODE_SOLVER_BACKEND = "torchdiffeq"
RELATION_WEIGHT_INIT = 0.1
ODE_DROPOUT = 0.0
ODE_USE_GRAPH = True
ODE_USE_CONTROL = True

DEFAULT_LIMIT_BLOCKS = 5
TRAIN_PROTOTYPE_LIMIT_BLOCKS = 10
TRAIN_PROTOTYPE_EPOCHS = 20
FULL_PIPELINE_TRAIN_EPOCHS = 0
TRAIN_CHECKPOINT_DIR = PROJECT_ROOT / "outputs" / "checkpoints"
TRAIN_EARLY_STOPPING_PATIENCE = 5
TRAIN_MIN_DELTA = 1e-4
LOSS_WEIGHT_CLASSIFICATION = 1.0
LOSS_WEIGHT_INITIAL_ALIGNMENT = 0.05
LOSS_WEIGHT_SMOOTHNESS = 0.01
LOSS_WEIGHT_MUTUAL_EXCLUSION = 0.01
LOSS_WEIGHT_REGRESSION = 0.05
LEARNING_RATE = 0.01
PRINT_SAMPLES = 5

DIVISION_EPSILON = 1e-6
PROBABILITY_MIN = 0.0
PROBABILITY_MAX = 1.0

REFLECTION_MAX_ROUNDS = 10
REFLECTION_CONFIDENCE_THRESHOLD = 0.70
REFLECTION_HIGH_CONFIDENCE_THRESHOLD = 0.85
REFLECTION_MIN_WEAK_DIMS = 2
REFLECTION_ODE_MARGIN_THRESHOLD = 0.10
REFLECTION_ARGUMENT_CONFIDENCE_THRESHOLD = 0.55
REFLECTION_STABILITY_THRESHOLD = 0.02
